opensearch-project/dashboards-reporting

- package.json
- yarn.lock
Signed-off-by: Rupal Mahajan <maharup@amazon.com>
- Upgrade json5 to v2.2.2
- Upgrade glob-parent to v6.0.2
CVE-2022-46175
CVE-2021-35065
> Upgrade json5 and glob-parent

- public/components/visual_report/generate_report.ts
Signed-off-by: Joshua Li <joshuali925@gmail.com>
Force scrollX and scrollY to be zero instead of actual values, otherwise if user scrolls down or right, the image will have a blank margin on top or left
> Update scrollX and scrollY values for html2canvas

- public/components/visual_report/generate_report.ts
Signed-off-by: Joshua Li <joshuali925@gmail.com>
(cherry picked from commit 7a60ae8a95968d8f977cfc5a48984789e240f20b)
Force scrollX and scrollY to be zero instead of actual values, otherwise if user scrolls down or right, the image will have a blank margin on top or left
> [aos-2.3.0.0] Update scrollX and scrollY config for html2canvas (#34)

- .github/workflows/dashboards-reports-release-workflow.yml
- .github/workflows/dashboards-reports-test-and-build-workflow.yml
The GitHub workflow uses the `engines` from OSD incorrectly. This change fixes that.
> Fix Node.js and Yarn installation in CI

- package.json
- yarn.lock
request is coming from jsdom dependency.
```
yarn why v1.22.19
[1/4] Why do we have the module "request"...?
[2/4] Initialising dependency graph...
warning Resolution field "json-schema@0.4.0" is incompatible with requested version "json-schema@0.2.3"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^4.1.0"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "request@2.88.2"
info Reasons this module exists
- "jsdom" depends …
```
> Update jsdom version to remove request dependency

- server/utils/__tests__/validationHelper.test.ts
- server/utils/validationHelper.ts
Notebooks after nav bar change has a new URL `observability-notebooks`, allow it in validation
> Support new notebooks URL

- public/components/context_menu/context_menu.js
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4453
Modified the breadcrumbs from the dashboard plugin, to be consistent with the actual name of the application.
We should consider not hard checking the name of the breadcrumb but really hooking into the navigation
plugin that provides the ability to do what this
logic is doing without being hardcoded.
This is related to but does not resolve:
https://github.com/opensearch-project/dashboards-reporting/issues/118
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-c …
> Update breadcrumb title of isDashboardNavMenu

- public/components/visual_report/assets/report_styles.ts
- public/components/visual_report/generate_report.ts
Make the generated report use the correct background color
Also:
* Remove font and color overrides from generated reports
* Remove side-nav from the exported report
* Avoid creating a footer when it has no content
* Fix report dimensions
[test12_2023-08-10T05 49 37.983Z_b12ad400-3741-11ee-a3da-f9dc44b8dbe5.pdf](https://github.com/opensearch-project/dashboards-reporting/files/12316434/test12_2023-08-10T05.49.37.983Z_b12ad400-3741-11ee-a3da-f9dc44b8dbe5.pdf)
[Test23_2023-08-30T20 18 35.215Z_65a3edf0-4772-11ee-bd7a-cb1f0be60683.pdf](https://github.com/opensearch-project/dashboards-reporting/files/12479876/Test23_2023-08-30T20.18.35.215Z_65a3edf0-4772-11ee-bd7a-cb1f0be60683.pdf)
Fixes #111 
Fixes opensearch-project/OpenSearch-Dashboards#3979
opensearch-project/reporting#735 - Part 1
By …
> Make the generated report use the correct background color

- public/components/context_menu/context_menu.js
- server/utils/__tests__/validationHelper.test.ts
- server/utils/validationHelper.ts
- discover url changed to data-explorer and discoverLegacy, update the server validations accordingly
- core menu classname and children length changed. temporarily fix those for now. long term fix should be using registerMenuItem API and tracked in https://github.com/opensearch-project/dashboards-reporting/issues/118
> support reporting for new discover

- public/components/context_menu/context_menu.js
- public/components/context_menu/context_menu_helpers.js
> Fix reporting discover

- server/routes/utils/__tests__/savedSearchReportHelper.test.ts
- server/routes/utils/dataReportHelpers.ts
Date format of nested fields are modified according to advanced settingsDate format of nested fields according to advanced settings
#106 
> Fix date format in csv files

- server/routes/utils/dataReportHelpers.ts
Adding a condition to check if the date Field is included in the selected fields
> 2.11 Bug fix for checking Date Field presence

- public/components/context_menu/context_menu_helpers.js
- public/components/utils/application_service.ts
- public/components/utils/settings_service.ts
- public/plugin.ts
Use core navigation instead of hard coding URLs 
Fix #227 
> Use core navigation instead of hard coding URLs

- server/routes/lib/createReport.ts
- server/routes/utils/__tests__/savedSearchReportHelper.test.ts
- server/routes/utils/dataReportHelpers.ts
- server/routes/utils/savedSearchReportHelper.ts
Use Timezone in Reports
I don't know where the Documentation should be added, as I did not found any before
https://github.com/opensearch-project/dashboards-reporting/issues/54
> Feature Use Timezone in Reports

- package.json
- yarn.lock
Bump browserify-sign to address CVE-2023-46234
> Bump browserify-sign to address CVE-2023-46234

- package.json
- yarn.lock
Signed-off-by: Derek Ho <dxho@amazon.com>
(cherry picked from commit a23dbbbf67c9e5399ee53ac910c3f9f019a845a6)
> [2.x] Bump browserify-sign (#240)

- server/routes/utils/dataReportHelpers.ts
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>
(cherry picked from commit 8a9ac2ffa3b0477f6258cb2cd0f82d13b59ef544)
> Manually backport 2.11 Bug fix for checking Date Field presence (#211) to 2.10

- .github/workflows/ftr-e2e-reporting-test.yml
Add FTR e2e test workflow for dashboards reporting
> [CI/CD] Add FTR e2e test workflow for dashboards reporting

- .cypress/integration/04-download.spec.ts
- public/components/context_menu/context_menu.js
> Reporting menu item

- server/utils/__tests__/validationHelper.test.ts
- server/utils/validationHelper.ts
Currently regex doesn't allow durations with negative intervals like `PT-30M`, which is a valid ISO 8601 duration. This PR fixes it
> allow negative signs in duration

- .github/workflows/cypress-e2e-reporting-test.yml
- .github/workflows/ftr-e2e-reporting-test.yml
- .github/workflows/lint.yml
On behalf of the change in dashboards core: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5675. We need to add `--single-version=loose` flag during the bootstrap step in our CI to manipulate the behavior of single-version validation. 
* Resolve the CI failure: https://github.com/opensearch-project/dashboards-observability/actions/runs/7964135017/job/21741091909?pr=1447#step:16:231
> [CI/CD] Add single version flag during bootstrap to fix version conflicts

- server/routes/utils/__tests__/savedSearchReportHelper.test.ts
- server/routes/utils/dataReportHelpers.ts
- Added condition to check if date is undefined.
https://github.com/opensearch-project/dashboards-reporting/issues/308
> Fix undefined date error while generating CSV report

- .github/workflows/verify-binary-installation.yml
I have observed some issues within other plugins of issues being only caught at run time. This is because several things can go wrong during the build process, which may not be caught in a dev setup. This adds a workflow to verify that building and installing into OSD works on every PR.
Related issues:
https://github.com/opensearch-project/security-dashboards-plugin/issues/1709
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/875
There was also an issue in this repo that was fixed when we caught a similar issue during release testing. Context is here: https://github.com/opensearch-project/dashboards-observability/pull/309. Here is a test run proving this PR would have caught that issue during RC testing: …
> Add workflow to verify binary installation is successful

- package.json
- yarn.lock
- Add package resolution for browserify-sign, debug and @babel/traverse
CVE-2023-45133, CVE-2017-16137, CVE-2023-46234
> Fix CVE-2023-45133, CVE-2017-16137, CVE-2023-46234

- package.json
- public/components/context_menu/context_menu.js
- public/components/context_menu/context_menu_ui.js
- public/components/main/main_utils.tsx
- public/components/report_definitions/report_settings/report_settings.tsx
- public/components/report_definitions/report_settings/report_settings_constants.tsx
- server/model/backendModel.ts
- server/model/index.ts
- server/routes/utils/__tests__/savedSearchReportHelper.test.ts
- server/routes/utils/constants.ts
- server/routes/utils/converters/backendToUi.ts
- server/routes/utils/dataReportHelpers.ts
- server/routes/utils/excelBuilder.ts
- server/routes/utils/savedSearchReportHelper.ts
- server/routes/utils/types.ts
- yarn.lock
XLSX support added
This feature aims to improve the user experience by providing dynamic and visually appealing reports. Some enhancements are applied by default to make report more friendly to users
* Header row freeze
* Bold and aligned header text
* Auto filter for each column
* Column width adjusted by content
This PR is part of improvements and should be merged in conjuction with opensearch-project/reporting#940
Closes #274
Please check report …
> Add xlsx support

- package.json
- yarn.lock
build is failing with below error without `--single-version=loose`
```
ERROR [single_version_dependencies] Multiple version ranges for the same dependency
were found declared across different package.json files. Please consolidate
those to match across all package.json files. Different versions for the
same dependency is not supported.
If you have questions about this please reach out to the operations team.
The conflicting dependencies are:
@types/dompurify
^3.0.5 => opensearch-dashboards
^2.3.3 => reports-dashboards
dompurify
^3.0.11 => opensearch-dashboards
^2.4.1 => reports-dashboards
error Command failed with exit code 1.
```
For …
> Update dompurify version

- public/components/context_menu/context_menu.js
Check if URL has `#` before split
https://github.com/opensearch-project/dashboards-reporting/issues/281
> Fix url parsing

- public/plugin.ts
- public/plugin_nav.tsx
This change adds a function that registers all the plugins to their corresponding NavGroups and NavCategories:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/tackadam/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/tackadam/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
</head>
<body link="#0563C1" vlink="#954F72">
Plug-in | Group | Category
-- | -- | --
Reports | Observability | …
> [Navigation] Register all plugins to NavGroups

- package.json
- yarn.lock
backport https://github.com/opensearch-project/dashboards-reporting/pull/381
#377 
> [Backport 2.x] Update dependency jsdom to v18

- package.json
- yarn.lock
this PR bumps ws to 7.5.10 and forces braces to resolve to ^3.0.3
CVE-2024-37890, CVE-2024-4068
> Bump ws to 7.5.10 and braces to 3.0.3

- public/components/main/main.tsx
Remove unused import. Already back-ported
> [Bug] Remove unused import

- package.json
- yarn.lock
Upgrade micromatch to 4.0.8 
https://nvd.nist.gov/vuln/detail/CVE-2024-4067
> Upgrade micromatch to 4.0.8 

- package.json
- yarn.lock
* updated micromatch dependency to 4.0.8
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
* add resolution for micromatch
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
---------
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
(cherry picked from commit f9a236da4fad3ea4dad1d2eda5efaaf7b28ec112)
Backport for https://github.com/opensearch-project/dashboards-reporting/pull/423
https://nvd.nist.gov/vuln/detail/CVE-2024-4067
> [Backport 2.x] Upgrade micromatch to 4.0.8  (#423)

- package.json
- yarn.lock
* updated micromatch dependency to 4.0.8
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
* add resolution for micromatch
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
---------
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
(cherry picked from commit f9a236da4fad3ea4dad1d2eda5efaaf7b28ec112) (cherry picked from commit e2748078e74c901ad20a57d98ddbd60a862896d1)
Backport for https://github.com/opensearch-project/dashboards-reporting/pull/423
https://nvd.nist.gov/vuln/detail/CVE-2024-4067
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBU …
> [Backport 2.17] Upgrade micromatch to 4.0.8  (#423)

- .cypress/integration/02-edit.spec.ts
- public/components/main/report_definition_details/report_definition_details.tsx
- public/components/main/report_details/report_details.tsx
- public/components/report_definitions/report_settings/report_settings.tsx
- release-notes/opensearch-dashboards-reporting.release-notes-2.17.0.0.md
Manual backport of #395 
#328 
> [Manual Backport] Allow arbitrary report record counts

- public/components/report_definitions/report_settings/report_settings.tsx
Updating the UX on the warning per UX feedback
N/A
> Update large record report warning

- package.json
- release-notes/opensearch-dashboards-reporting.release-notes-2.17.0.0.md
- yarn.lock
Bump path-to-regexp to 1.9.0
Resolves CVE: https://github.com/advisories/GHSA-9wv6-86v2-598j
> Bump path-to-regexp to 1.9.0

- yarn.lock
[CVE-2024-45801] Bump `dompurify` from 2.4.7 to 2.5.6
> [CVE-2024-45801] Bump `dompurify` from 2.4.7 to 2.5.6

- .github/workflows/cypress-e2e-reporting-test.yml
- .github/workflows/dashboards-reports-test-and-build-workflow.yml
- .github/workflows/ftr-e2e-reporting-test.yml
- public/plugin_nav.tsx
Based on https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8332, reporting needs to make some adjustment to flatten the menus in analytics(all) use case.
> [navigation]feat: update category to flatten menus in analytics(all) use case

- package.json
- yarn.lock
> [2.18] CVE fix dompurify@3.1.2

- public/components/main/__tests__/__snapshots__/main.test.tsx.snap
- public/components/main/__tests__/__snapshots__/reports_table.test.tsx.snap
- public/components/report_definitions/report_settings/report_settings.tsx
Fix missing imports removed by https://github.com/opensearch-project/dashboards-reporting/pull/431
> [2.18] Fix missing imports in report_settings

- server/routes/utils/dataReportHelpers.ts
In some cases, the sorting field gets unwrapped from a nested list to just a list. I'm not sure why. But adding this guard clause would avoid further damage when it happens.
Resolves #371 
> Guard against invalid sorting fields in report generation

- public/components/main/__tests__/__snapshots__/main.test.tsx.snap
- public/components/main/__tests__/__snapshots__/reports_table.test.tsx.snap
- public/components/report_definitions/report_settings/report_settings.tsx
When generating report we are sanitizing the header/footer. For consistency also sanitize them during create/edit report.
> Sanitize markdown when previewing report header/footer

- server/routes/utils/__tests__/savedSearchReportHelper.test.ts
- server/routes/utils/dataReportHelpers.ts
On generating a CSV report from a saved search in Dashboards, nestsed fields for the index pattern was not getting parsed in the picture below
RCA:
the [code](https://github.com/opensearch-project/dashboards-reporting/blob/main/server/routes/utils/dataReportHelpers.ts#L306) piece handling the nested fields only checked if the fields had a key with a . in them, it was ignoring the fields which had an array of objects to be added to the CSV file, the fix handles the nested array objects which are needed as a part of the nested fields
The fix handles all nested fields which were getting truncated
https://github.com/opensearch-project/dashboards-reporting/issues/375
For more …
> [BUG]Csv report generation had missing nested Fields

- package.json
- yarn.lock
Downgrade cypress version to 12.17.4 to match Opensearch Dashboards
Reporting plugin is failing in dashboards 2.19.0 distribution build because of different cypress versions:
```
ERROR [single_version_dependencies] Multiple version ranges for the same dependency
were found declared across different package.json files. Please consolidate
those to match across all package.json files. Different versions for the
same dependency is not supported.
If you have questions about this please reach out to the operations team.
The conflicting dependencies are:
cypress
12.17.4 => opensearch-dashboards
^13.6.0 => reports-dashboards
```
For more …
> Downgrade cypress to 12.17.4

- package.json
- yarn.lock
Manual backport for #508 to 2.19
> [Backport 2.19] [CVE-2024-21538] Bump cross-spawn from 6.0.5 and 7.0.3 to 7.0.5 (#508)

- package.json
- yarn.lock
> [CVE-2024-47875] Bump dompurify to 3.2.4

- package.json
- yarn.lock
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
Co-authored-by: Ritvi Bhatt <ribhatt@amazon.com>
(cherry picked from commit 2d0e662e1923b80c31edd61ee3d64023eb86687e)
Manual backport for #511 to 2.19
> [Backport 2.19] [CVE-2024-47875] Bump dompurify from 3.1.6 to 3.2.4 (#511)

- package.json
- yarn.lock
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
Co-authored-by: Ritvi Bhatt <ribhatt@amazon.com>
(cherry picked from commit 2d0e662e1923b80c31edd61ee3d64023eb86687e)
Manual backport for #511 for 2.x
> [Backport 2.x] [CVE-2024-47875] Bump dompurify from 3.1.6 to 3.2.4 (#511)

- package.json
- yarn.lock
Change dompurify version to 3.0.11 to match OSD
Different versions are causing build issues 
```
dompurify
^3.0.11 => opensearch-dashboards
^3.2.4 => reports-dashboards
```
> Change dompurify version to 3.0.11 to match OSD

- public/components/report_definitions/create/create_report_definition.tsx
- public/components/report_definitions/delivery/delivery.tsx
- public/components/report_definitions/report_settings/report_settings.tsx
- public/components/report_definitions/report_trigger/report_trigger.tsx
- public/components/report_definitions/utils/utils.tsx
- server/model/backendModel.ts
- server/model/index.ts
- server/routes/utils/__tests__/savedSearchReportHelper.test.ts
- server/routes/utils/converters/__tests__/backendToUi.test.ts
- server/routes/utils/converters/backendToUi.ts
- server/routes/utils/converters/uiToBackend.ts
- server/utils/__tests__/validationHelper.test.ts
While generating reports the time picker which shows the time from and time to is not working
it auto selects the range as 'Now' and the duration specified, This happens to the edit functionality of the reports as well.
Fix after
https://github.com/user-attachments/assets/401ec030-7b92-4647-89e9-d77f240377e3
https://github.com/opensearch-project/dashboards-reporting/issues/414
> [Bug]Support for date range in report generation

- package.json
- yarn.lock
`jspdf` introdcues old dompurify with security vulnerabilities. The 3.0 version fixes these vulnerabilities and doesn't have breaking changes. 
CVE-2025-26791
> Bump jspdf to 3.0 to fix CVE-2025-26791

- .github/workflows/cypress-e2e-reporting-test.yml
- .github/workflows/dashboards-reports-test-and-build-workflow.yml
- .github/workflows/ftr-e2e-reporting-test.yml
- .github/workflows/verify-binary-installation.yml
- opensearch_dashboards.json
- package.json
Bump dashboards reporting to version 3.0.0.0-alpha1
https://github.com/opensearch-project/dashboards-reporting/issues/150
>  Bump dashboards reporting to version 3.0.0.0-alpha1

- package.json
- release-notes/opensearch-dashboards-reporting.release-notes-3.0.0.0-alpha1.md
- yarn.lock
CVE fix for elliptic GHSA-vjh7-7g9h-fjfh and update release notes, Removed the dev dependency of osd lint. We anyways use the es lint script. 
Before 
```
❯ npm ls elliptic
reports-dashboards@3.0.0.0-alpha1 /Users/sgguruda/work/git_codebase/OpenSearch-Dashboards/plugins/dashboards-reporting
├─┬ @elastic/eslint-import-resolver-kibana@npm:@osd/eslint-import-resolver-opensearch-dashboards@2.0.0 invalid: "link:../../packages/osd-eslint-import-resolver-opensearch-dashboards" from the root project -> ./../../packages/osd-eslint-import-resolver-opensearch-dashboards
│ └─┬ webpack@npm:@amoo-miki/webpack@4.46.0-xxhash.1 invalid: ">=1.11.0" from ../../node_modules/eslint-import-resolver-webpack
│   └─┬ node-libs-browser@2.2.1
│     └─┬ crypto-browserify@3.12.0
│       ├─┬ browserify-sign@4.2.2
│ …
```
> CVE fix for elliptic and update release notes

- server/model/index.ts
- server/routes/utils/converters/backendToUi.ts
When loading reports which did not have a time from and time to there was an error thrown saying error generating report, making the parameters optional 
> [Bug] Updated the optional parameters for timefrom and timeto

- package.json
- yarn.lock
bump jspdf to 3.0.1
CVE-2025-29907
> bump jspdf to 3.0.1

- .cypress/integration/04-download.spec.ts
- public/components/context_menu/context_menu.js
- public/components/context_menu/context_menu_helpers.js
- public/components/context_menu/context_menu_ui.js
The reporting pop-over for dashboards was set to a fixed position, if the user scrolled down the page and clicked it, it would be hidden as it appeared at the top.
This change makes it relative so the pop-over always opens correctly.
Before:
https://github.com/user-attachments/assets/939c3f93-ef4e-4c16-ae49-b7a2c0f3a40a
After:
https://github.com/user-attachments/assets/0a5d90c6-9119-4ddc-92d0-70ec528cb074
Also updated the failing cypress test. The original code was looking for 
cy.get('#generatePDF > span:nth-child(1) > span:nth-child(2)').click({ force: true });
but only one exist
Changed to :  cy.get('#generatePDF').click({ force: true }); and is passing
https://github.com/opensearch-project/dashboards-reporting/issues/401
By submitting this pull request, I confirm that my contribution …
> [Bug] Reporting Popover UI

- yarn.lock
Fixes CVE 2025-5889. Follows https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9903: deleting yarn.lock entry and running yarn osd bootstrap again.
> Fix CVE 2025-5889
