DEVELOPER_GUIDE.md
Signed-off-by: Rupal Mahajan <maharup@amazon.com>
Add changes wrt new repo in Developer guide
=> Update Developer guide

release-notes/opensearch-dashboards-reporting.release-notes-2.5.0.0.md
=> Add release notes for 2.5.0.0

package.json
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
Updating plugin-helpers in package.json
https://github.com/opensearch-project/reporting/issues/626
=> Updating plugin-helpers in package.json

public/components/visual_report/generate_report.ts
Signed-off-by: Joshua Li <joshuali925@gmail.com>
(cherry picked from commit 7a60ae8a95968d8f977cfc5a48984789e240f20b)
=> [aos-1.3.2.0] Update scrollX and scrollY config for html2canvas (#34)

public/components/visual_report/generate_report.ts
=> [1.2] Update scrollX and scrollY config for html2canvas (#34)

public/components/visual_report/generate_report.ts
=> [aos-1.1.0.0] Update scrollX and scrollY config for html2canvas (#34)

public/components/visual_report/generate_report.ts
=> [aos-1.0.0.0-ga] Update scrollX and scrollY config for html2canvas (#34)

.github/workflows/dashboards-reports-test-and-build-workflow.yml, .github/workflows/draft-release-notes-workflow.yml, opensearch_dashboards.json, package.json
Signed-off-by: Divya Madala <divyaasm@amazon.com>
Version incremented from 1.3.7 to 1.3.8
=> Increment version to 1.3.8

.github/workflows/dashboards-reports-test-and-build-workflow.yml, .github/workflows/draft-release-notes-workflow.yml, opensearch_dashboards.json, package.json
- Incremented version to 2.6.0-SNAPSHOT.
https://github.com/opensearch-project/dashboards-reporting/issues/19
=> Increment version to 2.6.0-SNAPSHOT

.github/workflows/dashboards-reports-test-and-build-workflow.yml, .github/workflows/draft-release-notes-workflow.yml, opensearch_dashboards.json, package.json
Signed-off-by: Divya Madala <divyaasm@amazon.com>
Bump version from 1.3.8 to 1.3.9
=> Increment version to 1.3.9

release-notes/opensearch-dashboards-reporting.release-notes-2.6.0.0.md
=> Add release notes for 2.6.0

release-notes/opensearch-dashboards-reporting.release-notes-2.6.0.0.md
=> add one missinng infra item

.github/workflows/dashboards-reports-test-and-build-workflow.yml, .github/workflows/draft-release-notes-workflow.yml, opensearch_dashboards.json, package.json
=> bump version

release-notes/opensearch-dashboards-reporting.release-notes-2.7.0.0.md
- added release notes for 2.7.0
=> Add release notes for 2.7.0

release-notes/opensearch-dashboards-reports.release-notes-1.3.10.0.md
=> Add release notes for 1.3.10.0

release-notes/opensearch-dashboards-reporting.release-notes-2.8.0.0.md
=> Add release notes for 2.8

release-notes/opensearch-dashboards-reporting.release-notes-2.9.0.0.md
=> Add 2.9 release notes

package.json, yarn.lock
=> bump word-wrap for cve fix

.github/workflows/backport.yml
=> fail backport workflow

release-notes/opensearch-dashboards-reports.release-notes-1.3.12.0.md
=> Add release notes for 1.3.12

package.json, yarn.lock
- Add @cypress/request to resolutions for CVE-2023-28155 
- CVE-2023-28155
=> Bump @cypress/request to 3.0.0

release-notes/opensearch-dashboards-reporting.release-notes-2.10.0.0.md
=> Add 2.10 Release notes

package.json, yarn.lock
=> Upgrade debug and other deps

public/components/context_menu/context_menu.js
This change will add reporting back to discover
=> Support reporting in discover

release-notes/opensearch-dashboards-reporting.release-notes-2.11.0.0.md
Signed-off-by: Peter Fitzgibbons <peter.fitzgibbons@gmail.com>
=> Release Notes 2.11

package.json, yarn.lock
Upgrade traverse to address CVE-2023-45133, resolve debug for CVE-2017-16137
=> Upgrade traverse to address CVE-2023-45133, resolve debug for  CVE-2017-16137

package.json, yarn.lock
Upgrade traverse to address CVE-2023-45133, resolve debug for CVE-2017-16137
=> Upgrade traverse to address CVE-2023-45133, resolve debug for CVE-2017-16137

release-notes/opensearch-dashboards-reporting.release-notes-2.11.1.0.md
Signed-off-by: Peter Fitzgibbons <peter.fitzgibbons@gmail.com>
Release Notes 2.11.1
=> Release Notes 2.11.1

.github/workflows/ftr-e2e-reporting-test.yml
Add E2E FTR workflow for Dashboards Reporting
* Backport #264 
=> [Backport 2.x] Add E2E FTR workflow for Dashboards Reporting

.cypress/.eslintrc.js, .eslintignore, .eslintrc, .eslintrc.js, .github/workflows/lint.yml, package.json
=> [CI/CD] Add eslint workflow

.cypress/.eslintrc.js, .eslintignore, .eslintrc, .eslintrc.js, .github/workflows/lint.yml, package.json
[Backport 2.x] Add eslint workflow
=> [Backport 2.x] Add eslint workflow

release-notes/opensearch-dashboards-reporting.release-notes-2.12.0.0.md
=> Added release notes for 2.12

release-notes/opensearch-dashboards-reports.release-notes-1.3.15.0.md
- Added 1.3.15.0 release notes
=> Add 1.3.15.0 release notes

package.json, public/components/context_menu/context_menu.js, public/components/context_menu/context_menu_ui.js, public/components/main/main_utils.tsx, public/components/report_definitions/report_settings/report_settings.tsx, public/components/report_definitions/report_settings/report_settings_constants.tsx, server/model/backendModel.ts, server/model/index.ts, server/routes/utils/__tests__/savedSearchReportHelper.test.ts, server/routes/utils/constants.ts, server/routes/utils/converters/backendToUi.ts, server/routes/utils/dataReportHelpers.ts, server/routes/utils/excelBuilder.ts, server/routes/utils/savedSearchReportHelper.ts, server/routes/utils/types.ts, yarn.lock
Signed-off-by: Danila Gulderov <danila@gulderov.me>
Signed-off-by: Rupal Mahajan <maharup@amazon.com>
Co-authored-by: Rupal Mahajan <maharup@amazon.com>
(cherry picked from commit a8118062a4f94961a9234ac9e7347750199ee23f)
backport #275
=> [2.x] Add xlsx support (#275)

public/components/context_menu/context_menu_ui.js
=> fix menu cut off

.github/workflows/cypress-e2e-reporting-test.yml, .github/workflows/ftr-e2e-reporting-test.yml
- Updated version to 2.13  in cypress and ftr workflows
=> Update version in workflows

release-notes/opensearch-dashboards-reporting.release-notes-2.13.0.0.md
=> added release notes

release-notes/opensearch-dashboards-reporting.release-notes-2.14.0.0.md
=> Add 2.14.0 release notes

public/components/context_menu/context_menu_ui.js
=> [Look&Feel] Adjust header and text sizes in reporting menu options

package.json, yarn.lock
Update ws resolution to v7.5.10
https://github.com/opensearch-project/dashboards-reporting/issues/377
CVE-2024-37890 
=> Update dependency ws to v7.5.10

package.json, yarn.lock
backport https://github.com/opensearch-project/dashboards-reporting/pull/385
https://github.com/opensearch-project/dashboards-reporting/issues/377
=> [Backport 2.x] Update dependency ws to v7.5.10

package.json, yarn.lock
- Added braces v3.0.3 to resolution
CVE-2024-4068
=> Add braces v3.0.3 to resolution

release-notes/opensearch-dashboards-reporting.release-notes-2.16.0.0.md
=> Add v2.16.0 release notes

package.json, yarn.lock
backport https://github.com/opensearch-project/dashboards-reporting/pull/388
=> [Backport 2.x] Add braces v3.0.3 to resolution

opensearch_dashboards.json, public/plugin.ts
De-registering Reporting when MDS is enabled
=> [Enhancement] De-register reporting when MDS is enabled

release-notes/opensearch-dashboards-reporting.release-notes-2.17.0.0.md
Release notes for 2.17
(https://github.com/opensearch-project/dashboards-reporting/issues/399)
=> Add v2.17 release notes

public/components/report_definitions/report_settings/report_settings.tsx
=> [Manual backport] Update report with many records warning

release-notes/opensearch-dashboards-reporting.release-notes-2.17.1.0.md
Add release note for 2.17.1
* Related 2.17.1 patch release
=> Add release note for 2.17.1

release-notes/opensearch-dashboards-reporting.release-notes-2.17.1.0.md
Fix release note for 2.17.1
* Related 2.17.1 patch release
=> Fix the release note for 2.17.1

package.json, yarn.lock
=> [Backport 2.18] CVE fix for dompurify@3.0.11

release-notes/opensearch-dashboards-reporting.release-notes-2.18.0.0.md
[Release 2.18] Add release notes for 2.18
* Relate Release Version 2.18
=> [Release 2.18] Add release notes for 2.18

package.json, public/components/report_definitions/report_settings/report_settings.tsx, server/routes/utils/constants.ts, yarn.lock
Address CVE issues of
- [CVE-2024-45801 HIGH](https://advisories.opensearch.org/advisories/CVE-2024-45801)
- [CVE-2024-47875 HIGH](https://advisories.opensearch.org/advisories/CVE-2024-47875)
- [CVE-2024-4067 MEDIUM](https://advisories.opensearch.org/advisories/CVE-2024-4067)
- [CVE-2024-4067 MEDIUM](https://advisories.opensearch.org/advisories/CVE-2024-4067)
- [CVE-2024-45296 HIGH](https://advisories.opensearch.org/advisories/CVE-2024-45296)
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develope …
=> [CVE] Address CVE issues

release-notes/opensearch-dashboards-reporting.release-notes-2.18.0.0.md
[Backport 2.x] Release note 2.18
Release Version 2.18
=> [Backport 2.x] Release note 2.18

release-notes/opensearch-dashboards-reporting.release-notes-2.19.0.0.md
=> Add release notes for 2.19.0

release-notes/opensearch-dashboards-reporting.release-notes-2.19.1.0.md
Add release notes for 2.19.1 
https://github.com/opensearch-project/dashboards-reporting/issues/507
=> Add release notes for 2.19.1 

release-notes/opensearch-dashboards-reporting.release-notes-3.0.0.0-aplha1.md
Add release notes for 3.0.0-aplha1
=> Add release notes for 3.0.0-aplha1

.github/workflows/cypress-e2e-reporting-test.yml, .github/workflows/dashboards-reports-test-and-build-workflow.yml, .github/workflows/ftr-e2e-reporting-test.yml, .github/workflows/link-checker.yml, .github/workflows/lint.yml, .github/workflows/verify-binary-installation.yml, DEVELOPER_GUIDE.md, MAINTAINERS.md, README.md
Minor CI updates and workflow fixes
Derived from this PR https://github.com/opensearch-project/dashboards-reporting/pull/547
=> Minor CI updates and workflow fixes

.github/workflows/cypress-e2e-reporting-test.yml, .github/workflows/dashboards-reports-test-and-build-workflow.yml, .github/workflows/ftr-e2e-reporting-test.yml, .github/workflows/verify-binary-installation.yml, opensearch_dashboards.json, package.json
=> Bump version to 3.0.0-beta1

package.json, yarn.lock
=> bump jspdf to 3.0.1 (#555)

package.json, yarn.lock
=> [CVE] fix CVE issue CVE-2025-27789

release-notes/opensearch-dashboards-reporting.release-notes-2.19.2.0.md
=> 2.19.2 release notes

release-notes/opensearch-dashboards-reporting.release-notes-3.0.0.0.md
Add release notes for 3.0.0.0
https://github.com/opensearch-project/opensearch-build/issues/3747#issuecomment-2836369925
=> Release notes for 3.0.0.0

release-notes/opensearch-dashboards-reporting.release-notes-3.1.0.0.md
Adding release notes for 3.1.0
#580 
=> Adding release notes for 3.1.0

server/routes/utils/__tests__/savedSearchReportHelper.test.ts, server/routes/utils/dataReportHelpers.ts
Further breakdown of nested fields
certain nested fields had no objects present due to nested json not being considered when downloading CSV when added as a selected field this would fix it 
=> [Bug] Deserialization of nested fields, missing values of nested fields
